#!/bin/sh

# Modified markdown files: update modDatetime if already published
git diff --cached --name-status |
  grep -Ei '^(M).*(src/data/blog).*\.(md)$' |
  while read _ file; do
    [ -f "$file" ] || continue
    filecontent=$(cat "$file")
    frontmatter=$(echo "$filecontent" | awk -v RS='---' 'NR==2{print}')
    draft=$(echo "$frontmatter" | awk '/^draft: /{print $2}')

    if [ "$draft" = "false" ]; then
      echo "$file modDatetime updated"
      sed "/^---$/,/^---$/s/^modDatetime:.*$/modDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" "$file" >tmp && mv tmp "$file"
      git add "$file"
    fi

    if [ "$draft" = "first" ]; then
      echo "First release of $file, draft set to false and modDatetime cleared"
      sed -e "/^---$/,/^---$/s/^modDatetime:.*$/modDatetime:/" \
        -e "/^---$/,/^---$/s/^draft:.*$/draft: false/" "$file" >tmp && mv tmp "$file"
      git add "$file"
    fi
  done

# Newly added markdown files: stamp pubDatetime
git diff --cached --name-status |
  grep -Ei '^(A).*(src/data/blog).*\.(md)$' |
  while read _ file; do
    [ -f "$file" ] || continue
    echo "$file pubDatetime stamped"
    sed "/^---$/,/^---$/s/^pubDatetime:.*$/pubDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" "$file" >tmp && mv tmp "$file"
    git add "$file"
  done

exit 0
